name: CI/CD for QA Project

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4

    - name: Install Node.js
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: '16'

    - name: Install Newman
      run: npm install -g newman

    - name: Check for required secrets
      run: |
        if [ -z "${{ secrets.API_URL }}" ] || [ -z "${{ secrets.API_KEY }}" ]; then
          echo "API_URL or API_KEY is not set. Skipping tests."
          exit 0
        fi

    - name: Replace placeholders in environment file
      run: |
        sed -i 's|https://api.example.com/v3|${{ secrets.API_URL }}|' prod.postman_environment.json
        sed -i 's/placeholder-key/${{ secrets.API_KEY }}/' prod.postman_environment.json
      env:
        API_URL: ${{ secrets.API_URL }}
        API_KEY: ${{ secrets.API_KEY }}

    - name: Run Newman Tests
      run: |
        newman run testsuite_1.json -e prod.postman_environment.json -r json --reporter-json-export newman-results.json
      env:
        API_URL: ${{ secrets.API_URL }}
        API_KEY: ${{ secrets.API_KEY }}

    - name: Run generate-csv.js
      run: node generate-csv.js

    - name: Upload Results
      uses: actions/upload-artifact@v3  # Update if used, otherwise it's fine to keep the existing version
      with:
        name: summary-results
        path: summary_results.csv
